services:
  fl-server:
    build:
      context: .                    # Root project sebagai context
      dockerfile: server/Dockerfile
    container_name: fl-server
    ports:
      - "5000:5000"
    restart: unless-stopped

  client-waru:
    build:
      context: .                    # Root project sebagai context
      dockerfile: clients/base/Dockerfile
    container_name: client-waru
    ports:
      - "5001:5001"
    volumes:
      - ./clients/waru/data:/app/data
    environment:
      - CLIENT_NAME=waru
      - CLIENT_PORT=5001
      - LOCAL_EPOCHS=3
    depends_on:
      - fl-server
    restart: unless-stopped

  client-kemiri:
    build:
      context: .
      dockerfile: clients/base/Dockerfile
    container_name: client-kemiri
    ports:
      - "5002:5001"
    volumes:
      - ./clients/kemiri/data:/app/data
    environment:
      - CLIENT_NAME=kemiri
      - CLIENT_PORT=5001
      - LOCAL_EPOCHS=3
    depends_on:
      - fl-server
    restart: unless-stopped

  client-nangsri:
    build:
      context: .
      dockerfile: clients/base/Dockerfile
    container_name: client-nangsri
    ports:
      - "5003:5001"
    volumes:
      - ./clients/nangsri/data:/app/data
    environment:
      - CLIENT_NAME=nangsri
      - CLIENT_PORT=5001
      - LOCAL_EPOCHS=3
    depends_on:
      - fl-server
    restart: unless-stopped
